### ISSUE TITLE
feature request: login/sign-in authentication

### ISSUE THREAD

**Issue by amandaratio** [sfitzgerald16/rsrc-mobile#1]
the profile button on the bottom navigation will lead a user to this page if they are not already signed in

sign-in/login page will have two input fields:
-email
-password

at the bottom there is (obviously) a button to submit and log-in.

if users do not have an account there will be two separate links:
-sign-up as organization
-sign-up as user

**Comment by lindsgray** [comment]
this is technically done because of the linkin
