### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by lindsgray** [sfitzgerald16/rsrc-mobile#22]
login page should be minimalist w/ input fields for the username and password w/ a submit button at the bottom. below the submit button will be texting prompting the user to sign up should they not have an account.

in ionic this page tends to have an option for a cover photo as well as an icon. these images have already been created and will be input upon the close of this issue.

**Comment by shaala** [comment]
![issue 22_loginscreen](https://user-images.githubusercontent.com/33503572/33586172-d05b74f8-d91c-11e7-931d-9dbc6353ffc7.jpg)
